version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    ports:
      - "5432:5432"
  redis-stack:
    image: redis/redis-stack-server:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
    restart: unless-stopped
