spring:
  application:
    name: location-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
    pool:
      initial-size: 10
      max-size: 20
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    repair-required: true
  data:
    r2dbc:
      repositories:
        enabled: true
    redis:
      host: localhost
      port: 6379
      cache-properties:
        USERS_BY_ID:
          cache-name: LOCATION:USERS_BY_ID
          expiryPolicy: PT24H
        PLACES_BY_ID:
          cache-name: LOCATION:PLACES_BY_ID
          expiryPolicy: PT24H



logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    org.springframework.cache: DEBUG
    angrymiaucino.locationservice.service.PlaceService: DEBUG
